import * as _dungeon from './dungeon';
import * as _dungeons from './dungeons';
import * as _dungeonEnemies from './dungeonEnemies';
import * as _dungeonEnemy from './dungeonEnemy';
import * as _dungeonGate from './dungeonGate';
import * as _dungeonGates from './dungeonGates';
import * as _dungeonMedicine from './dungeonMedicine';
import * as _dungeonMedicines from './dungeonMedicines';
import * as _dungeonWeapon from './dungeonWeapon';
import * as _dungeonWeapons from './dungeonWeapons';
import * as _enemy from './enemy';
import * as _enemies from './enemies';
import * as _location from './location';
import * as _locations from './locations';
import * as _medicine from './medicine';
import * as _medicines from './medicines';
import * as _weapon from './weapon';
import * as _weapons from './weapons';
import * as _player from './player';
import * as _store from './store';

export const dungeon = _dungeon;
export const dungeons = _dungeons;
export const dungeonEnemies = _dungeonEnemies;
export const dungeonEnemy = _dungeonEnemy;
export const dungeonGate = _dungeonGate;
export const dungeonGates = _dungeonGates;
export const dungeonMedicine = _dungeonMedicine;
export const dungeonMedicines = _dungeonMedicines;
export const dungeonWeapon = _dungeonWeapon;
export const dungeonWeapons = _dungeonWeapons;
export const enemy = _enemy;
export const enemies = _enemies;
export const location = _location;
export const locations = _locations;
export const medicine = _medicine;
export const medicines = _medicines;
export const weapon = _weapon;
export const weapons = _weapons;
export const player = _player;
export const store = _store;
