enum ItemTypes {
  DUNGEON_PLAYER = 'DUNGEON_PLAYER',
  DARKNESS = 'DARKNESS',
  GROUND = 'GROUND',
  WALL = 'WALL',
  DUNGEON_ENEMY = 'DUNGEON_ENEMY',
  DUNGEON_WEAPON = 'DUNGEON_WEAPON',
  DUNGEON_MEDICINE = 'DUNGEON_MEDICINE',
  DUNGEON_GATE = 'DUNGEON_GATE'
}

export default ItemTypes;
